/*Generated by xorm v0.5.5.0728 2016-08-22 12:53:49*/

CREATE TABLE IF NOT EXISTS "Limit" ("Id" SERIAL PRIMARY KEY  NOT NULL, "Name" VARCHAR(255) NULL, "Updated" TIMESTAMP NULL);
INSERT INTO "Limit" ("Id", "Name", "Updated") VALUES (1, '1', '2016-08-22 12:53:49 +0000 +0000');

CREATE TABLE IF NOT EXISTS "customtablename" ("Id" SERIAL PRIMARY KEY  NOT NULL, "Name" VARCHAR(255) NULL);

CREATE TABLE IF NOT EXISTS "CreatedInsert2" ("Id" SERIAL PRIMARY KEY  NOT NULL, "Created" BIGINT NULL);
INSERT INTO "CreatedInsert2" ("Id", "Created") VALUES (1, 1471841628);

CREATE TABLE IF NOT EXISTS "Picture" ("Id" SERIAL PRIMARY KEY  NOT NULL, "Url" VARCHAR(255) NULL, "Title" VARCHAR(255) NULL, "Description" VARCHAR(255) NULL, "Created" TIMESTAMP NULL, "ILike" INTEGER NULL, "PageView" INTEGER NULL, "From_url" VARCHAR(255) NULL, "Pre_url" VARCHAR(255) NULL, "Uid" BIGINT NULL);
CREATE UNIQUE INDEX "UQE_Picture_Pre_url" ON "Picture" ("Pre_url");
CREATE UNIQUE INDEX "UQE_Picture_Url" ON "Picture" ("Url");

CREATE TABLE IF NOT EXISTS "Userinfo" ("id" SERIAL PRIMARY KEY  NOT NULL, "Username" VARCHAR(255) NULL, "Departname" VARCHAR(255) NULL, "Created" TIMESTAMP NULL, "detail_id" INTEGER NULL, "Height" DOUBLE PRECISION NULL, "Avatar" BYTEA NULL, "IsMan" BOOL NULL);
CREATE UNIQUE INDEX "UQE_Userinfo_Username" ON "Userinfo" ("Username");
INSERT INTO "Userinfo" ("id", "Username", "Departname", "Created", "detail_id", "Height", "Avatar", "IsMan") VALUES (6, 'xlw11', 'dev', '2016-08-22 12:53:49 +0000 +0000', 0, 0, 0x, false);
INSERT INTO "Userinfo" ("id", "Username", "Departname", "Created", "detail_id", "Height", "Avatar", "IsMan") VALUES (7, 'xlw22', 'dev', '2016-08-22 12:53:49 +0000 +0000', 0, 0, 0x, false);
INSERT INTO "Userinfo" ("id", "Username", "Departname", "Created", "detail_id", "Height", "Avatar", "IsMan") VALUES (8, '1xlw', 'dev', '2016-08-22 12:53:49 +0000 +0000', 0, 0, 0x, false);
INSERT INTO "Userinfo" ("id", "Username", "Departname", "Created", "detail_id", "Height", "Avatar", "IsMan") VALUES (9, '1xlw2', 'dev', '2016-08-22 12:53:49 +0000 +0000', 0, 0, 0x, false);
INSERT INTO "Userinfo" ("id", "Username", "Departname", "Created", "detail_id", "Height", "Avatar", "IsMan") VALUES (10, '1xlw11', 'dev', '2016-08-22 12:53:49 +0000 +0000', 0, 0, 0x, false);
INSERT INTO "Userinfo" ("id", "Username", "Departname", "Created", "detail_id", "Height", "Avatar", "IsMan") VALUES (11, '1xlw22', 'dev', '2016-08-22 12:53:49 +0000 +0000', 0, 0, 0x, false);
INSERT INTO "Userinfo" ("id", "Username", "Departname", "Created", "detail_id", "Height", "Avatar", "IsMan") VALUES (12, 'xlw3', 'dev', '2016-08-22 12:53:49 +0000 +0000', 0, 0, 0x, false);
INSERT INTO "Userinfo" ("id", "Username", "Departname", "Created", "detail_id", "Height", "Avatar", "IsMan") VALUES (4, 'xlw', 'dev', '2016-08-22 12:53:49 +0000 +0000', 0, 0, 0x, false);

CREATE TABLE IF NOT EXISTS "Userdetail" ("Id" SERIAL PRIMARY KEY  NOT NULL, "Intro" TEXT NULL, "Profile" VARCHAR(2000) NULL);
INSERT INTO "Userdetail" ("Id", "Intro", "Profile") VALUES (1, 'I''m a very beautiful women.', 'sfsaf');

CREATE TABLE IF NOT EXISTS "Numeric" ("Numeric" NUMERIC NULL);

CREATE TABLE IF NOT EXISTS "CreatedInsert" ("Id" SERIAL PRIMARY KEY  NOT NULL, "Created" TIMESTAMP NULL);
INSERT INTO "CreatedInsert" ("Id", "Created") VALUES (1, '2016-08-22 12:53:48 +0000 +0000');

CREATE TABLE IF NOT EXISTS "CreatedInsert3" ("Id" SERIAL PRIMARY KEY  NOT NULL, "Created" BIGINT NULL);
INSERT INTO "CreatedInsert3" ("Id", "Created") VALUES (1, 1471841628);

CREATE TABLE IF NOT EXISTS "CreatedInsert4" ("Id" SERIAL PRIMARY KEY  NOT NULL, "Created" INTEGER NULL);
INSERT INTO "CreatedInsert4" ("Id", "Created") VALUES (1, 1471841628);

CREATE TABLE IF NOT EXISTS "CreatedInsert5" ("Id" SERIAL PRIMARY KEY  NOT NULL, "Created" BIGINT NULL);
INSERT INTO "CreatedInsert5" ("Id", "Created") VALUES (1, 1471841628);

CREATE TABLE IF NOT EXISTS "MyJsonTime" ("Id" SERIAL PRIMARY KEY  NOT NULL, "Created" TIMESTAMP NULL);
INSERT INTO "MyJsonTime" ("Id", "Created") VALUES (1, '2016-08-22 12:53:48 +0000 +0000');

CREATE TABLE IF NOT EXISTS "DefaultInsert" ("Id" SERIAL PRIMARY KEY  NOT NULL, "Status" INTEGER NULL DEFAULT '-1'::integer, "Name" VARCHAR(255) NULL, "Created" TIMESTAMP NULL, "Updated" TIMESTAMP NULL);
INSERT INTO "DefaultInsert" ("Id", "Status", "Name", "Created", "Updated") VALUES (1, -1, 'test', '2016-08-22 12:53:48 +0000 +0000', '2016-08-22 12:53:48 +0000 +0000');

CREATE TABLE IF NOT EXISTS "DefaultInsert2" ("Id" SERIAL PRIMARY KEY  NOT NULL, "Name" VARCHAR(255) NULL, "Url" TEXT NULL, "CheckTime" TIMESTAMP NOT NULL DEFAULT ''2000-01-01 00:00:00'::timestamp without time zone');
INSERT INTO "DefaultInsert2" ("Id", "Name", "Url", "CheckTime") VALUES (1, 'test', '', '2000-01-01 00:00:00 +0000 +0000');

CREATE TABLE IF NOT EXISTS "NoIdUser" ("User" VARCHAR(255) NULL, "Remain" BIGINT NULL, "Total" BIGINT NULL);
CREATE UNIQUE INDEX "UQE_NoIdUser_User" ON "NoIdUser" ("User");
INSERT INTO "NoIdUser" ("User", "Remain", "Total") VALUES ('xlw', 20, 100);

CREATE TABLE IF NOT EXISTS "Users" ("Uid" UUID PRIMARY KEY NOT NULL, "UserName" VARCHAR(30) NOT NULL, "NickName" VARCHAR(30) NOT NULL, "Password" VARCHAR(44) NOT NULL, "Email" VARCHAR(80) NOT NULL, "profile_id" UUID NULL, "CreatedAt" timestamp with time zone NOT NULL, "UpdatedAt" timestamp with time zone NOT NULL, "created_user_id" UUID NULL, "update_user_id" UUID NULL);
CREATE UNIQUE INDEX "UQE_Users_Email" ON "Users" ("Email");
CREATE UNIQUE INDEX "UQE_Users_UserName" ON "Users" ("UserName");
INSERT INTO "Users" ("Uid", "UserName", "NickName", "Password", "Email", "profile_id", "CreatedAt", "UpdatedAt", "created_user_id", "update_user_id") VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'sfafdafds', 'sfsfds', 'ssss', 'llll@123.com', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '2016-08-22 12:53:49.205289 +0800 CST', '2016-08-22 12:53:49.205301 +0800 CST', NULL, NULL);

CREATE TABLE IF NOT EXISTS "Profile" ("Uid" UUID PRIMARY KEY NOT NULL, "user_id" VARCHAR(50) NULL, "CreatedAt" timestamp with time zone NOT NULL, "UpdatedAt" timestamp with time zone NOT NULL, "created_user_id" VARCHAR(50) NULL, "update_user_id" VARCHAR(50) NULL);
INSERT INTO "Profile" ("Uid", "user_id", "CreatedAt", "UpdatedAt", "created_user_id", "update_user_id") VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', NULL, '2016-08-22 12:53:49.20657 +0800 CST', '2016-08-22 12:53:49.206577 +0800 CST', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', NULL);
